//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBDAdvance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personne
    {
        public decimal idPersonne { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string mail { get; set; }
        public string GSM { get; set; }
        public string Fix { get; set; }
    
        public virtual MedecinResponsable MedecinResponsable { get; set; }
        public virtual Travailleur Travailleur { get; set; }
    }
}
