//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBDAdvance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisiteMedicale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VisiteMedicale()
        {
            this.ExamenPratiques = new HashSet<ExamenPratique>();
        }
    
        public decimal idVisite { get; set; }
        public System.DateTime date { get; set; }
        public decimal codeEmploi { get; set; }
        public decimal idType { get; set; }
        public decimal idPersonne { get; set; }
    
        public virtual Emploi Emploi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamenPratique> ExamenPratiques { get; set; }
        public virtual MedecinResponsable MedecinResponsable { get; set; }
        public virtual TypeLieu TypeLieu { get; set; }
    }
}
